micronaut:
  application:
    name: microliqui2

---
dataSources:
  default:
    pooled: true
    jmxExport: true
    dbCreate: none
    url: jdbc:postgresql://localhost:5432/bookliquidb
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
jpa:
  default:
    packages-to-scan:
      - microliqui2.domain
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.groovy'
